name: shellcheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt install shellcheck
    - name: run shellcheck
      run: |
        shellcheck *.sh
